<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wm_pagepath"
 *
 * Auto generated by Extension Builder 2018-08-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'wm_pagepath',
    'description' => 'Generates Frontend URL from Backend',
    'category' => 'services',
    'author' => 'Sascha Löffler',
    'author_email' => 'sloeffler@webmatch.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
